// @ts-nocheck
const BRIDGE_ACTIONS = {
    SET_SELECTED_ASSET_TYPE: 'SET_SELECTED_ASSET_TYPE',
    SET_SENDER_ASSET_CURRENT_BALANCE: 'SET_SENDER_ASSET_CURRENT_BALANCE',
    SET_SENDER_ASSET_TARGET_BALANCE: 'SET_SENDER_ASSET_TARGET_BALANCE',
    SET_SENDER_NATIVE_TOKEN_PUBLIC_BALANCE: 'SET_SENDER_NATIVE_TOKEN_PUBLIC_BALANCE',
    SET_SENDER_PUBLIC_ACCOUNT: 'SET_SENDER_PUBLIC_ACCOUNT',
    SET_SENDER_PUBLIC_ACCOUNT_OPTIONS: 'SET_SENDER_PUBLIC_ACCOUNT_OPTIONS',
  };
  
  export default BRIDGE_ACTIONS;
  