const SEND_ACTIONS = {
  TOGGLE_SENDER_ACCOUNT_IS_PRIVATE: 'TOGGLE_SENDER_ACCOUNT_IS_PRIVATE',
  TOGGLE_RECEIVER_ACCOUNT_IS_PRIVATE: 'TOGGLE_RECEIVER_ACCOUNT_IS_PRIVATE',
  CHANGE_SENDER_ASSET_TYPE: 'CHANGE_SENDER_ASSET_TYPE',
  SET_SENDER_ASSET_TYPE: 'SET_SENDER_ASSET_TYPE',
  SET_SENDER_ASSET_CURRENT_BALANCE: 'SET_SENDER_ASSET_CURRENT_BALANCE',
  SET_SENDER_PUBLIC_ACCOUNT: 'SET_SENDER_PUBLIC_ACCOUNT',
  SET_SENDER_PUBLIC_ACCOUNT_OPTIONS: 'SET_SENDER_PUBLIC_ACCOUNT_OPTIONS',
  SET_RECEIVER: 'SET_RECEIVER'
};

export default SEND_ACTIONS;
