import React, { useState } from 'react';
import { Form, Grid, Header, Input } from 'semantic-ui-react';
import { TxButton } from './substrate-lib/components';

export default function Main ({ accountPair, wasm }) {
  const [formState, setFormState] = useState({ address: null, amount: 0 });
  const onChange = (_, data) =>
    setFormState(prev => ({ ...prev, [data.state]: data.value }));

  const [status, setStatus] = useState(null);

  /** Data needed */

  // assetID -> form (or 1)

  // reclaimAmount -> form

  // sender_coin1, sender_coin2: MantaAsset {
  //  asset_id -> 1 for now
  //  utxo -> on chain (how to get?)
  //  void number -> on chain
  //  pk -> keyring
  //  rho -> random
  //  s -> random
  //  r -> random
  //  k -> from WASM function?
  // }


  // receiver MantaAssetProcessedReceiver {
  // utxo -> ??
  // shielded address -> generated by reclaimer (wasm?)
  // value -> form
  // sender pk -> keyring
  // ciphertext -> ??
  // }

  return (
    <>
      <Grid.Column width={2}/>
      <Grid.Column width={12}>
        <Header textAlign='center'>Reclaim Private Asset</Header>
        <Form>
        <Form.Field style={{ width: '500px', marginLeft: '2em' }}>
          <Input
              fluid
              label='Asset ID'
              type='number'
              state='assetID'
              onChange={onChange}
            />
          </Form.Field>
          <Form.Field style={{ width: '500px', marginLeft: '2em' }}>
            <Input
              fluid
              label='Amount'
              type='number'
              state='reclaimAmount'
              onChange={onChange}
            />
          </Form.Field>
          <Form.Field style={{ textAlign: 'center' }}>
            <TxButton
              accountPair={accountPair}
              label='Submit'
              type='SIGNED-TX'
              setStatus={setStatus}
              attrs={{
                palletRpc: 'mantaPay',
                callable: 'reclaim',
                inputParams: [],
                paramFields: []
              }}
            />
          </Form.Field>
          <div style={{ overflowWrap: 'break-word' }}>{status}</div>
        </Form>
      </Grid.Column>
      <Grid.Column width={2}/>
    </>
  );
}
